## Philip Menke

## these functions provide a way to calculate and cache the inverse
## of a matrix so it would not have to be repeadeadly calculated

## Generates a list which contain functions to get and set
## a matrix as well as it's inverse.
##
## These variables will be kept in the list function returns
## and the list will be kept in the environment of which the function is called
##
## @param x a matrix
## @return a list containing functions that can be used on x
makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL #need to clear our cache since x changed
    }
    get <- function() x
    setinv <- function(inverse) inv <<- inverse
    getinv <- function() inv
    list(set = set, get = get,
         setinv = setinv,
         getinv = getinv)
}

##
## Checks if list already has a cached result and if so returns that.
## else will calculate the inverse of matrix kept in x
##
## @param x a list generated by makeCacheMatrix
## @param .. any additional flags to be parameters in solve()
## @return the inverse of the matrix contained in x

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    inv <- x$getinv()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data,...)
    x$setinv(inv)
    inv
}
